CREATE TABLE IF NOT EXISTS `incubationprogram` (
  `inid` INT AUTO_INCREMENT PRIMARY KEY,
  `VentureName` VARCHAR(255) NOT NULL,
  `FounderName` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `IndustrySector` VARCHAR(100) NOT NULL,
  `Stage` VARCHAR(50) NOT NULL,
  `MotivationStatement` TEXT NOT NULL,
  `CreatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 